@startuml


scale 620 width
scale 620 height

!theme toy

skinparam headerFontSize 20
header "Figure 1"
@startuml
!theme lightgray

title Enhancing FHIR for Social Services

class Individual {
identifier:Identifier
name : HumanName
address:Address
birthdate : Date
gender : Code
martialStatus : Code
communication : communication
}

 

ScreeningGroup : identifier :Identifier
ScreeningGroup : category : Code
ScreeningGroup : type : Code
ScreeningGroup : status : Code

class ScreeningGroup {

}

class LifeSet {
    
+ individual : Individual
}

LifeSet : category : Code
LifeSet : type : Code
 

Individual "*" <--o "0" LifeSet : association

Individual "*" <--o "1" ScreeningGroup : member

   

 

   
 
@enduml