@startuml


scale 620 width
scale 620 height

!theme toy

skinparam headerFontSize 20
header "Figure 1"
@startuml
!theme lightgray

title Enhancing FHIR for Social Services

class Individual {
active: boolean
identifier:Identifier
name : HumanName
address:Address
birthdate : Date
gender : Code
martialStatus : Code
communication : communication
}

 

ScreeningSet : identifier :Identifier
ScreeningSet : category : Code
ScreeningSet : type : Code
ScreeningSet : status : Code

class ScreeningSet {

}

 
  

ScreeningSet "0..*" - "1..1" Individual
(ScreeningSet, Individual) .. Membership

class Membership {
   tyoe : Code
   effectiveTime : Date
   effectiveTiming : Timing
   status : Code
   verification : Code
   qualificatoin : Qualification
   
}
 


   
 
@enduml