@startuml

title Enhancing FHIR for Social Services

class Person

class ProgramGroup {

}

class LifeGroup {

}

Person "*" <--o "1" LifeGroup : PatientRole


   

 

   

SNAP --|> Program 

class SNAP {

}

note left of SNAP
 For instance, a sample rule for SNAP would be  all group members to be above 18
end note

SECTION_8 --|> Program 

class SECTION_8 {

}

@enduml